### PR TITLE
moved name to string conversion outside if statement

### PR DESCRIPTION
**Pull request by 1-w**
Fix for #126

### CODE REVIEW

**Comment by arnaudbore** [comment]
Hi @1-w ,

I took a look at what you suggest in your PR. I tested it with a simple case and even with your fix I end up with the same error.

The only way I've got this working, if I put `"EchoTime": "0.00298"` instead of `"EchoTime": 0.00298` in the config file. It was not working before but now it does with your fix.

I'm not really familiar with the regex part of dcm2bids (legacy code) that's why I was not confident enough to put `name = str(name)` for the regex condition. I was afraid it would break something when using "complex" regex expression.  It would be nice, if you can provide some documentation and tests added to this PR. It would make the whole review processing smoother. I would like also to know why re.match will be a better suit for regex expression comparison compare to re.search ?

One last thing, I don't see how your modifications in `dcm2bids/utils.py` are related to the issue/PR or need to be fixed. I would need some clarification here.

Thank you

**Comment by 1-w** [comment]
Hey @arnaudbore,

thanks a lot for the reply.

> The only way I've got this working, if I put `"EchoTime": "0.00298"` instead of `"EchoTime": 0.00298` in the config file. It was not working before but now it does with your fix.

I think this is due to the config values being passed to re matching, which is expecting a regex, not a float. "0.00298" works but would match 0\<any char\>00298. To match the "." exactly you would have to pass "0\\.00298" (in quotes!).

> I was afraid it would break something when using "complex" regex expression. It would be nice, if you can provide some documentation and tests added to this PR. It would make the whole review processing smoother.

I will do that. The (very small) fix now relates to the target value not being a string. It would of course make a lot of sense to check the config (so your example should raise a warning or error since its not a valid regex).

> One last thing, I don't see how your modifications in `dcm2bids/utils.py` are related to the issue/PR or need to be fixed. I would need some clarification here.

You are right, this second commit should not be in the pull request. It relates to a potential separate issue, which is not not handling errors raised by dependencies (in this case from pydeface). 


The whole problem I'm facing is this incredibly annoying edge case of someone having put special characters in the dcm header "seriesDescription", which causes some problems handling the filenames. I couldn't get fnmatch to work correctly and since I'm much more familiar with regex I went that route.

**Comment by arnaudbore** [comment]
Hi @1-w ,

It seems like have been falling into a black hole for a long time. Before I take to much time and go back into a black hole, can you make sure your branch is up to date and there is no conflict? It seems like you're a couple of commit behind origin/master. 
Please remove the dependancy to your pydeface as well. Thank you.

**Comment by arnaudbore** [comment]
This has been fixed in #167

**Comment by 1-w** [comment]
I'm sorry that I haven't had the time to update everything yet, so great that you fixed it!

**Pull request closed without merging**
